databases:
  - name: jewelrycommerce-db
    plan: free

services:
  - type: web
    name: jewelrycommerce
    env: node
    autoDeploy: true
    buildCommand: |
      npm ci
      npm run db:enable:pgcrypto
      npm run db:push
      npm run build
      npm run db:seed
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jewelrycommerce-db
          property: connectionString
    healthCheckPath: /
